---
- name: 'Update yum packages (yum -y update)'
  yum: name=* state=latest
  when: ((server_patch is undefined) or (server_patch is none) or (server_patch=="true"))

- name: 'Set SELinux to permissive mode'
  selinux:
    policy: targeted
    state: permissive

- name: 'Install required packages'
  yum:
    name:
      - java-11-openjdk-devel
      - mariadb-devel
      - mariadb
      - mariadb-server
      - chrony
    state: installed

- name: 'Install required packages - OS Version 7'
  yum:
    name:
      - MySQL-python
    state: installed
  when: ansible_distribution_major_version == "7"

- name: 'Install required packages - OS Version 8'
  yum:
    name:
      - python3-pyOpenSSL
      - python3-PyMySQL
    state: installed
  when: ansible_distribution_major_version == "8"

- name: 'Enable chrony service'
  service: name=chronyd state=started enabled=yes

